### PR TITLE
Deploy to Maven Central

### PR DESCRIPTION
**Pull request by gjoseph**
Hi there,

With this PR, deploying snapshots to Sonatype's OSSRH snapshots repo should work (through Travis, if I got the settings right).

If you want to deploy releases to Central yourself, I could assist in any further configuration. If you'd prefer, I could do it myself - I would just need to request extra permissions to deploy to com.eleet with my account to Sonatype, IIRC.

Cheers !

### CODE REVIEW

**Comment by bbuck** [comment]
First of all, thanks for the contribution! Before I merge it in, I just want to make sure that I fully understand what it's doing.

Forgive me for asking, but what potential benefits does this provide?

**Comment by gjoseph** [comment]
Hey Brandon,

No worries, happy to share. Here's a few things the PR provides:

- "stable" builds: a) by providing fixed version number for plugins (build/pluginManagement), you get more stable builds everywhere (otherwise, Maven tends to get whatever's available locally, or latest version, of plugins, and you're at the mercy of plugin bugs). TBH, I copy-pasted this section from other projects I have, but it's fairly sound. b) by providing some configuration for the enforcer plugin, we ensure we're running the build in a certain environment, particularly when doing a release
- configuration for scm and distributionManagement, which enable doing releases using maven-release-plugin, and simple mvn deploy's
- configuration for signage of release artifacts

All of the above should enable deploying releases to Maven Central (through Sonatype's OSSRH)

Additionally, the PR adds travis-ci configuration, so you could enable a travis-ci job, which will deploy snapshots to OSSRH continously. (I enabled it for my fork, from a branch where I changed the groupId where I have permissions: https://travis-ci.org/gjoseph/DragonConsole -> https://oss.sonatype.org/content/repositories/snapshots/net/incongru/com/eleet/dragonconsole/3.0.0-SNAPSHOT/

Finally, having snapshots AND releases available on Maven Central will simply enable devs and other projects to reuse DragonConsole conveniently in their projects without maintaining and building copies, forks or other subtrees, by simply adding a dependency to it.

Does this answer your questions ? Feel free to ask more details about anything :)

**Comment by bbuck** [comment]
No that sounds great. 

So what services am I going to register with to make this a thing? I assume sonatype, but I've not set up Travis builds before - you mentioned something about offering to help out here - what would you need to do that?

**Comment by gjoseph** [comment]
For Travis, it's easy: go to https://travis-ci.org/, login with your GitHub account. Go to "my repositories", and enable DragonConsole.

For the Travis build to be able to _deploy_ snapshots to the maven repos, you'll need to adapt the "secure" tokens in the `.travis.yml` file. These are a Sonatype user/pass, or token/token-pass, encrypted specifically for that particular build (so even if using my token, we'd need to reencrypt for those to work with your repo)

And lastly (or firstly, really), you need credentials with Sonatype. The guide is here: http://central.sonatype.org/pages/ossrh-guide.html

I already had an account since a long time, valid for /net/incongru/*, so I can't recall exactly the procedure there (and it might have changed since).

I also had to fiddle around a bit to sign artifacts, so that's another thing I copied from another project of mine.

My offer to help would simply be to do the releases for you. Sonatype will probably require some form of agreement/authorization from you, but if you're not familiar with the process, it'll probably just be easier (or happen faster). I could e.g do the 3.0 release, make sure it gets to central and all; meanwhile you could create your account with Sonatype and we make sure you're setup correctly to do the next release.

**Comment by bbuck** [comment]
I'll get to work on getting these requirements down and then I'll merge this in manually applying the necessary changes to IDs, etc...

Thanks for this!

**Comment by gjoseph** [comment]
Ok cool. Let me know if you need any help with anything specific.
I also noticed you'll need to add `<description>`, `<url>`, `<license>` and `<developers>` sections to your pom.xml.
Cheers

**Comment by bbuck** [comment]
Quick update here, I have been incredibly busy and haven't finished this yet, but I'm still working on it, I just wanted to let you know.

**Pull request closed without merging**
